# Generated by Django 2.2.5 on 2019-09-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('pk_countries', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Código DDI: ')),
                ('name_country', models.CharField(max_length=100, verbose_name='Nome: ')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('pk_language', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Símbolo: ')),
                ('name_laguage', models.CharField(max_length=50, verbose_name='Descrição: ')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_provinces', models.CharField(max_length=5, verbose_name='Símbolo da UF: ')),
                ('name_province', models.CharField(max_length=100, verbose_name='Nome: ')),
                ('country_symbol', models.CharField(max_length=5, verbose_name='Símbolo do País: ')),
                ('time_zone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário: ')),
                ('fk_countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Countries', verbose_name='País: ')),
            ],
            options={
                'verbose_name_plural': 'Provinces',
                'unique_together': {('pk_provinces', 'fk_countries')},
            },
        ),
        migrations.AddField(
            model_name='countries',
            name='fk_languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localization.Languages', verbose_name='Língua Oficial: '),
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('pk_cities', models.AutoField(primary_key=True, serialize=False, verbose_name='Código: ')),
                ('name_city', models.CharField(max_length=150, verbose_name='Nome: ')),
                ('zip_code', models.CharField(max_length=15, verbose_name='C.E.P.: ')),
                ('fk_provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.Provinces', verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'unique_together': {('fk_provinces', 'pk_cities')},
            },
        ),
    ]
