# Generated by Django 2.2.5 on 2019-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_remove_cities_fk_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='pk_cities',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código: '),
        ),
    ]
