# Generated by Django 2.2.5 on 2019-09-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnits',
            fields=[
                ('pk_baseunits', models.AutoField(primary_key=True, serialize=False, verbose_name='Código: ')),
                ('name_unit', models.CharField(max_length=50, verbose_name='Descrição: ')),
                ('unit_simbol', models.CharField(max_length=3, verbose_name='Unidade: ')),
                ('repr_unit', models.SmallIntegerField(default=1, verbose_name='Representação: ')),
            ],
            options={
                'verbose_name_plural': 'baseUnits',
            },
        ),
        migrations.CreateModel(
            name='NcmCategories',
            fields=[
                ('pk_ncmcategories', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Códigp: ')),
                ('name_ncmcat', models.CharField(max_length=200, verbose_name='Descrição: ')),
            ],
            options={
                'verbose_name_plural': 'ncmCategories',
            },
        ),
        migrations.CreateModel(
            name='TypeTaxes',
            fields=[
                ('pk_type_taxes', models.AutoField(primary_key=True, serialize=False, verbose_name='Códugo: ')),
                ('name_tax', models.CharField(max_length=50, verbose_name='Descrição: ')),
                ('flag_tax', models.SmallIntegerField(choices=[(1, 'ICMS'), (2, 'ICMS_ST'), (3, 'IPI'), (4, 'ISS'), (5, 'ISENTO'), (6, 'Outros')], default=1, verbose_name='Tipo de Imposto: ')),
            ],
            options={
                'verbose_name_plural': 'typeTaxes',
            },
        ),
        migrations.CreateModel(
            name='NcmCodes',
            fields=[
                ('pk_ncmcodes', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código: ')),
                ('name_ncm', models.TextField(verbose_name='Descrição: ')),
                ('flag_ipi', models.BooleanField(default=False, verbose_name='Incide IPI: ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de vigência Inicial: ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de vigência Final: ')),
                ('fk_baseunits', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxesaux.BaseUnits', verbose_name='Unidade: ')),
                ('fk_ncmcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxesaux.NcmCategories', verbose_name='Categoria: ')),
            ],
            options={
                'verbose_name_plural': 'ncmCodes',
            },
        ),
    ]
