# Generated by Django 2.2.5 on 2019-09-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxesaux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseunits',
            old_name='unit_simbol',
            new_name='unit_symbol',
        ),
        migrations.AddConstraint(
            model_name='baseunits',
            constraint=models.UniqueConstraint(fields=('unit_symbol',), name='baseunits_symbol_idx'),
        ),
    ]
