# Generated by Django 2.2.5 on 2019-09-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxesaux', '0002_auto_20190927_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseunits',
            options={'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelOptions(
            name='ncmcategories',
            options={'verbose_name_plural': 'Categoria NCM'},
        ),
        migrations.AlterModelOptions(
            name='ncmcodes',
            options={'verbose_name_plural': 'Tabela NCM'},
        ),
        migrations.AlterModelOptions(
            name='typetaxes',
            options={'verbose_name_plural': 'Tipos de Impostos'},
        ),
        migrations.RemoveConstraint(
            model_name='baseunits',
            name='baseunits_symbol_idx',
        ),
        migrations.AlterField(
            model_name='ncmcodes',
            name='flag_ipi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Aliquota IPI: '),
        ),
    ]
