# Generated by Django 2.2.5 on 2019-09-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxesaux', '0001_initial'),
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('pk_taxes', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código')),
                ('taxdef', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual: ')),
                ('fk_countries_destiny', models.ForeignKey(default=55, on_delete=django.db.models.deletion.PROTECT, related_name='pk_countries_destiny', related_query_name='countries_destiny', to='localization.Countries', verbose_name='País de Destino')),
                ('fk_countries_origin', models.ForeignKey(default=55, on_delete=django.db.models.deletion.PROTECT, related_name='pk_countries_origin', related_query_name='countries_origin', to='localization.Countries', verbose_name='País de Origem')),
                ('fk_states_destiny', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='pk_states_destiny', related_query_name='states_destiny', to='localization.States', verbose_name='Estado de Destino')),
                ('fk_states_origin', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='pk_states_origin', related_query_name='states_origin', to='localization.States', verbose_name='Estado de Origem')),
                ('fk_type_taxes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='taxesaux.TypeTaxes', verbose_name='Tipo de Imposto')),
            ],
            options={
                'verbose_name_plural': 'Impostos Default',
            },
        ),
        migrations.CreateModel(
            name='NcmTaxes',
            fields=[
                ('pk_ncmtaxes', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual')),
                ('fk_ncmcodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxesaux.NcmCodes', verbose_name='NCM do Produto')),
                ('fk_taxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.Taxes', verbose_name='Alíquota default')),
            ],
            options={
                'verbose_name_plural': 'Impostos Produtos NCM',
            },
        ),
        migrations.AddConstraint(
            model_name='taxes',
            constraint=models.UniqueConstraint(fields=('fk_type_taxes', 'fk_countries_origin', 'fk_states_origin', 'fk_countries_destiny', 'fk_states_destiny'), name='pk_taxes'),
        ),
        migrations.AddConstraint(
            model_name='ncmtaxes',
            constraint=models.UniqueConstraint(fields=('fk_taxes', 'fk_ncmcodes'), name='pk_ncmtaxes'),
        ),
    ]
