# Generated by Django 2.2.5 on 2019-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersContacts',
            fields=[
                ('pk_users_contacts', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('user_email', models.CharField(max_length=255, verbose_name='e-Mail')),
                ('user_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'db_table': 'home_users_contacts',
            },
        ),
        migrations.CreateModel(
            name='UsersTests',
            fields=[
                ('pk_users_tests', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='e-Mail')),
                ('user_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('qtd_tests', models.IntegerField(verbose_name='Quant.')),
            ],
            options={
                'verbose_name_plural': 'Testes da API',
                'db_table': 'home_users_tests',
            },
        ),
    ]
