# Generated by Django 2.2.5 on 2019-09-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_cnsm', models.BooleanField(default=False, verbose_name='Consumidor Final')),
                ('flag_block', models.BooleanField(default=False, verbose_name='Cliente Bloqueado')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limite de Crédito: ')),
                ('date_block', models.DateTimeField(blank=True, null=True, verbose_name='Data do Bloqueio: ')),
                ('mot_block', models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio: ')),
                ('fk_registers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registers.Registers', verbose_name='Usuário: ')),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
