# Generated by Django 2.2.5 on 2019-09-29 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('pk_registers', models.AutoField(primary_key=True, serialize=False, verbose_name='Código: ')),
                ('flag_treg', models.SmallIntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='Tipo: ')),
                ('main_doc', models.CharField(max_length=20, unique=True, verbose_name='Documento de Identificação: ')),
                ('secondary_doc', models.CharField(max_length=30, verbose_name='Outro Documento: ')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome: ')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome: ')),
                ('alias_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia: ')),
                ('enterprise_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa: ')),
                ('insert_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro: ')),
                ('kc_registers_address', models.SmallIntegerField(default=0, verbose_name='KeyControl RegistersAddresses')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Login: ')),
            ],
            options={
                'verbose_name_plural': 'Pessoas e Empresas',
            },
        ),
        migrations.CreateModel(
            name='RegistersAddress',
            fields=[
                ('pk_registers_address', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código: ')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço: ')),
                ('number', models.IntegerField(verbose_name='Número: ')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento: ')),
                ('quarter', models.CharField(max_length=50, verbose_name='Bairro: ')),
                ('zip_code', models.CharField(max_length=15, verbose_name='C.E.P.: ')),
                ('fk_cities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localization.Cities', verbose_name='Cidade: ')),
                ('fk_registers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.Registers', verbose_name='Usuário: ')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AddIndex(
            model_name='registersaddress',
            index=models.Index(fields=['fk_cities', 'zip_code'], name='localization_idx'),
        ),
    ]
