# Generated by Django 2.2.5 on 2019-09-29 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersaddress',
            name='flag_taddr',
            field=models.SmallIntegerField(choices=[(1, 'Endereço Default'), (2, 'Endereço Residencial'), (3, 'Endereço Comercial'), (4, 'Endereço de Cobrança'), (5, 'Endereço de Entrega')], default=1, verbose_name='Typo'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='alias_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Login do Usuário'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='flag_treg',
            field=models.SmallIntegerField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='main_doc',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento de Identificação'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='pk_registers',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='secondary_doc',
            field=models.CharField(max_length=30, verbose_name='Outro Documento'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='fk_cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localization.Cities', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='fk_registers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.Registers', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='pk_registers_address',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='quarter',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='zip_code',
            field=models.CharField(max_length=15, verbose_name='C.E.P.'),
        ),
    ]
