# Generated by Django 2.2.5 on 2019-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20190929_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='fk_categories',
            field=models.ManyToManyField(related_name='categorias', through='registers.RegistersCategories', to='registers.Categories', verbose_name='Categorias'),
        ),
    ]
