# Generated by Django 2.2.5 on 2019-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20190929_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='fk_categories',
            field=models.ManyToManyField(help_text='Selecione as categorias a qual este usuário pertence. Elas são criadas sempre como ativas, posteriormente pode-se alterar o campo "ativo" no menu "Categorias do Usuário".', related_name='registers_set', related_query_name='registers', through='registers.RegistersCategories', to='registers.Categories', verbose_name='Categorias'),
        ),
    ]
