# Generated by Django 2.2.5 on 2019-09-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_auto_20190929_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registers',
            options={'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='registerscategories',
            options={'verbose_name_plural': 'Categorias do Usuário'},
        ),
        migrations.AlterField(
            model_name='registers',
            name='fk_categories',
            field=models.ManyToManyField(help_text='Selecione as categorias a qual este usuário pertence. Elas são criadas sempre como ativas, posteriormente pode-se alterar o campo "ativo" no menu "Categorias do Usuário".', related_name='categories', through='registers.RegistersCategories', to='registers.Categories', verbose_name='Categorias'),
        ),
    ]
