# Generated by Django 2.2.5 on 2019-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_auto_20190929_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='registersaddress',
            name='flag_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='registersaddress',
            name='flag_taddr',
            field=models.SmallIntegerField(choices=[(1, 'Endereço Residencial'), (2, 'Endereço Comercial'), (3, 'Endereço de Cobrança'), (4, 'Endereço de Entrega')], default=1, verbose_name='Typo'),
        ),
    ]
